export enum EventType {
  GOAL = 'GOAL',
  YELLOW_CARD = 'YELLOW_CARD',
  RED_CARD = 'RED_CARD',
  SUBSTITUTION = 'SUBSTITUTION',
  FOUL = 'FOUL',
  SHOT = 'SHOT',
  CORNER = 'CORNER',
  OFFSIDE = 'OFFSIDE',
  PENALTY = 'PENALTY',
  FREE_KICK = 'FREE_KICK',
}
